# Generated by Django 5.2.7 on 2026-01-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicostatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando análise"),
                    ("analise_iniciada", "Análise iniciada"),
                    ("analise_concluida", "Análise concluída"),
                    ("emitida", "Carteira emitida"),
                    ("rejeitada", "Rejeitada"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando análise"),
                    ("analise_iniciada", "Análise iniciada"),
                    ("analise_concluida", "Análise concluída"),
                    ("emitida", "Carteira emitida"),
                    ("rejeitada", "Rejeitada"),
                ],
                default="aguardando",
                max_length=20,
            ),
        ),
    ]
