# Generated by Django 5.2.7 on 2026-02-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_alter_historicostatus_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="motivo_foto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qualidade", "Imagem com baixa qualidade/ilegível"),
                    ("invalido", "Documento não identificado ou inválido"),
                    ("desatualizado", "Documento fora da validade/antigo"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="motivo_laudo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qualidade", "Imagem com baixa qualidade/ilegível"),
                    ("invalido", "Documento não identificado ou inválido"),
                    ("desatualizado", "Documento fora da validade/antigo"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="motivo_rg_frente",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qualidade", "Imagem com baixa qualidade/ilegível"),
                    ("invalido", "Documento não identificado ou inválido"),
                    ("desatualizado", "Documento fora da validade/antigo"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="motivo_rg_verso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qualidade", "Imagem com baixa qualidade/ilegível"),
                    ("invalido", "Documento não identificado ou inválido"),
                    ("desatualizado", "Documento fora da validade/antigo"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="pendencia_foto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="pendencia_laudo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="pendencia_rg_frente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="pendencia_rg_verso",
            field=models.BooleanField(default=False),
        ),
    ]
